/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'buildProjectJSON' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Text],
      ['query'],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateAffirmations' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllChakras' : IDL.Func([], [IDL.Text], ['query']),
  'getAllKinesisEntries' : IDL.Func([], [IDL.Text], ['query']),
  'getBeliefSystems' : IDL.Func([], [IDL.Text], ['query']),
  'getFantasyMapping' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'listProjects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Int))],
      ['query'],
    ),
  'saveProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'buildProjectJSON' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Text],
        ['query'],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateAffirmations' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllChakras' : IDL.Func([], [IDL.Text], ['query']),
    'getAllKinesisEntries' : IDL.Func([], [IDL.Text], ['query']),
    'getBeliefSystems' : IDL.Func([], [IDL.Text], ['query']),
    'getFantasyMapping' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'listProjects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Int))],
        ['query'],
      ),
    'saveProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };