/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bot = IDL.Record({
  'id' : IDL.Nat,
  'personality' : IDL.Text,
  'name' : IDL.Text,
  'linkedWiki' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Text,
});
export const Memory = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'sentiment' : IDL.Int,
  'timestamp' : IDL.Int,
  'botId' : IDL.Nat,
  'memoryType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMemory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'buildProjectJSON' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Text],
      ['query'],
    ),
  'clearMemoriesForBot' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'removedCount' : IDL.Nat })],
      [],
    ),
  'createBot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteBot' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMemory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateAffirmations' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllBots' : IDL.Func([], [IDL.Vec(Bot)], ['query']),
  'getAllChakras' : IDL.Func([], [IDL.Text], ['query']),
  'getAllKinesisEntries' : IDL.Func([], [IDL.Text], ['query']),
  'getBeliefSystems' : IDL.Func([], [IDL.Text], ['query']),
  'getBot' : IDL.Func([IDL.Nat], [IDL.Opt(Bot)], ['query']),
  'getFantasyMapping' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMemoriesForBot' : IDL.Func([IDL.Nat], [IDL.Vec(Memory)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getRelevantMemories' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Vec(Memory)],
      ['query'],
    ),
  'listProjects' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Int))],
      ['query'],
    ),
  'saveProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bot = IDL.Record({
    'id' : IDL.Nat,
    'personality' : IDL.Text,
    'name' : IDL.Text,
    'linkedWiki' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Text,
  });
  const Memory = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'sentiment' : IDL.Int,
    'timestamp' : IDL.Int,
    'botId' : IDL.Nat,
    'memoryType' : IDL.Text,
  });
  
  return IDL.Service({
    'addMemory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'buildProjectJSON' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Text],
        ['query'],
      ),
    'clearMemoriesForBot' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'removedCount' : IDL.Nat })],
        [],
      ),
    'createBot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteBot' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMemory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateAffirmations' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllBots' : IDL.Func([], [IDL.Vec(Bot)], ['query']),
    'getAllChakras' : IDL.Func([], [IDL.Text], ['query']),
    'getAllKinesisEntries' : IDL.Func([], [IDL.Text], ['query']),
    'getBeliefSystems' : IDL.Func([], [IDL.Text], ['query']),
    'getBot' : IDL.Func([IDL.Nat], [IDL.Opt(Bot)], ['query']),
    'getFantasyMapping' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMemoriesForBot' : IDL.Func([IDL.Nat], [IDL.Vec(Memory)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getRelevantMemories' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Vec(Memory)],
        ['query'],
      ),
    'listProjects' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Int))],
        ['query'],
      ),
    'saveProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };