/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bot {
  'id' : bigint,
  'personality' : string,
  'name' : string,
  'linkedWiki' : [] | [string],
  'avatar' : string,
}
export interface Memory {
  'id' : bigint,
  'topic' : string,
  'content' : string,
  'sentiment' : bigint,
  'timestamp' : bigint,
  'botId' : bigint,
  'memoryType' : string,
}
export interface _SERVICE {
  'addMemory' : ActorMethod<[bigint, string, string, string, bigint], bigint>,
  'buildProjectJSON' : ActorMethod<
    [
      string,
      Array<string>,
      boolean,
      boolean,
      string,
      boolean,
      string,
      string,
      number,
      number,
      bigint,
      boolean,
      string,
      string,
      number,
      number,
      boolean,
      boolean,
      string,
      string,
      string,
      bigint,
      bigint,
    ],
    string
  >,
  'clearMemoriesForBot' : ActorMethod<[bigint], { 'removedCount' : bigint }>,
  'createBot' : ActorMethod<[string, string, string, [] | [string]], bigint>,
  'deleteBot' : ActorMethod<[bigint], boolean>,
  'deleteMemory' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'generateAffirmations' : ActorMethod<
    [string, boolean, boolean, boolean, string],
    Array<string>
  >,
  'getAllBots' : ActorMethod<[], Array<Bot>>,
  'getAllChakras' : ActorMethod<[], string>,
  'getAllKinesisEntries' : ActorMethod<[], string>,
  'getBeliefSystems' : ActorMethod<[], string>,
  'getBot' : ActorMethod<[bigint], [] | [Bot]>,
  'getFantasyMapping' : ActorMethod<[string], string>,
  'getMemoriesForBot' : ActorMethod<[bigint], Array<Memory>>,
  'getProject' : ActorMethod<[bigint], [] | [string]>,
  'getRelevantMemories' : ActorMethod<[bigint, string, bigint], Array<Memory>>,
  'listProjects' : ActorMethod<[], Array<[bigint, string, bigint]>>,
  'saveProject' : ActorMethod<[string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];