/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    buildProjectJSON(topic: string, affirmations: Array<string>, boosterEnabled: boolean, fantasyEnabled: boolean, fantasyInput: string, protectionEnabled: boolean, chakraName: string, voiceType: string, voiceSpeed: number, voicePitch: number, repetitionCount: bigint, whisperOverlay: boolean, backgroundMusicType: string, subliminalFrequency: string, musicVolume: number, subliminalVolume: number, waveformOverlay: boolean, stereoMovement: boolean, themeStyle: string, colorPalette: string, resolution: string, durationSeconds: bigint, frameRate: bigint): Promise<string>;
    deleteProject(id: bigint): Promise<boolean>;
    generateAffirmations(topic: string, boosterEnabled: boolean, fantasyEnabled: boolean, protectionEnabled: boolean, chakraName: string): Promise<Array<string>>;
    getAllChakras(): Promise<string>;
    getAllKinesisEntries(): Promise<string>;
    getBeliefSystems(): Promise<string>;
    getFantasyMapping(abilityName: string): Promise<string>;
    getProject(id: bigint): Promise<string | null>;
    listProjects(): Promise<Array<[bigint, string, bigint]>>;
    saveProject(title: string, jsonOutput: string): Promise<bigint>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async buildProjectJSON(arg0: string, arg1: Array<string>, arg2: boolean, arg3: boolean, arg4: string, arg5: boolean, arg6: string, arg7: string, arg8: number, arg9: number, arg10: bigint, arg11: boolean, arg12: string, arg13: string, arg14: number, arg15: number, arg16: boolean, arg17: boolean, arg18: string, arg19: string, arg20: string, arg21: bigint, arg22: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.buildProjectJSON(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buildProjectJSON(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async generateAffirmations(arg0: string, arg1: boolean, arg2: boolean, arg3: boolean, arg4: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAffirmations(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAffirmations(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllChakras(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChakras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChakras();
            return result;
        }
    }
    async getAllKinesisEntries(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKinesisEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKinesisEntries();
            return result;
        }
    }
    async getBeliefSystems(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBeliefSystems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBeliefSystems();
            return result;
        }
    }
    async getFantasyMapping(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFantasyMapping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFantasyMapping(arg0);
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<[bigint, string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return result;
        }
    }
    async saveProject(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProject(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
